### ISSUE TITLE
How did you initialize the weight of deconv layer with bilinear upsampling filter?

### ISSUE THREAD

**Issue by mks0601** [1adrianb/human-pose-estimation#3]
I`m using torch7 to implement my work.
I need to initialize the wieght of deconv layer with bilinear upsampling filter as yours in torch7.
Can you tell me how you did it?

**Comment by 1adrianb** [comment]
Hi @mks0601 ,

You can use the following function to initialize your filters:

```
local function upsample(size) -- size == filter height 
        local factor = math.floor((size+1)/2)
        local center
        if size % 2 == 1 then
                center = factor - 1
        else
                center = factor - 0.5
        end
        local grid = { torch.linspace(0,size-1,size):view(size,1),
                       torch.linspace(0,size-1,size):view(1,size) }
        return (1 - torch.abs(grid[1]-center)/factor) *
               (1 - torch.abs(grid[2]-center)/factor)
end
```
Of course, afterwards  you will need to initialize the weights of the deconvolution layer with the above filter.

**Comment by mks0601** [comment]
The generated filter has only spatial dimension. 
Then, do i have to copy the filter to all # of input channel * # of output channel dimensions?
(the dimension of SpatialFullConv layer is (# of input channel, # of output channel, height, width)). 

If so, it would generate the gray image if i feed a RGB image. 
What do you think?

**Comment by 1adrianb** [comment]
Not all of them if you want to keep it channel wise, more something like:

```
local w = torch.zeros(10,10,4,4)
local function fillWeights(w,inp,out,filter)
        for i = 1, inp do
                for j = 1, out do
                        if i==j then
                                w[{i,j,{},{}}] = filter
                        end
                end
        end
        return w
end
```
So only on the diagonal. Of course the code can be simplified  since in our case the number of channels from the input and output will be the same.

**Comment by mks0601** [comment]
Thanks for help!

**Comment by mks0601** [comment]
I initialized the weight of deconv layer as yours, however it does not generate the enlarged image correctly.
If i set kernelSz = 2, stride = 2, then it generate the darker 2x enlarged image(this is the same setting with yours). However, if i set kernelSz = 4, stride = 2, then it generate the 2x enlarged image correctly. Any help?

**Comment by 1adrianb** [comment]
Yes in order to apply interpolation the stride must be smaller than the kernel size, otherwise it will be similar with the nearest neighbour upsampling. Anyway, this was used only as a starting point since in the paper the deconvolutional layers were learned. (The initalisation was made in the same way as in the FCN paper pe J. Long)

**Comment by mks0601** [comment]
Yes thanks for help
To summarize, did you initialized the weight of deconv layer with the below code(channel-wise convolution)?

```local w = torch.zeros(10,10,4,4)
local function fillWeights(w,inp,out,filter)
        for i = 1, inp do
                for j = 1, out do
                        if i==j then
                                w[{i,j,{},{}}] = filter
                        end
                end
        end
        return w
end
```

**Comment by 1adrianb** [comment]
Yes, they were initialized using the method mentioned above.
